probando_municipalidad:
    resource: "@ProbandoBundle/Controller/MunicipalidadController.php"
    type:     annotation

probando:
    resource: "@ProbandoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
