<?php

namespace ProbandoBundle\Repository;

/**
 * municipalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class municipalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
