<?php

namespace ProbandoBundle\Repository;

/**
 * vemosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vemosRepository extends \Doctrine\ORM\EntityRepository
{
}
