ProbandoBundle_index:
    path:     /muni
    defaults: { _controller: "ProbandoBundle:Municipalidad:index" }
    methods:  GET

ProbandoBundle_show:
    path:     /{id}/show
    defaults: { _controller: "ProbandoBundle:Municipalidad:show" }
    methods:  GET

ProbandoBundle_new:
    path:     /new
    defaults: { _controller: "ProbandoBundle:Municipalidad:new" }
    methods:  [GET, POST]

ProbandoBundle_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProbandoBundle:Municipalidad:edit" }
    methods:  [GET, POST]

ProbandoBundle_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProbandoBundle:Municipalidad:delete" }
    methods:  DELETE
